name: My First Live Pipeline Test

on: [push]

jobs:
  run-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello to the Robot
        run: echo "The pipeline is working perfectly!"
        
      - name: Show Current Date and Time
        run: date
